name: dot_keygen
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/XLNT/dot_keygen
author: Matt Condon (shrugs) <matt@bydot.app>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  bitcoin_flutter: ^1.0.7
  web3dart: ^1.1.1+1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  urbit_ob: ^1.0.0
